<a href="https://colab.research.google.com/github/ParasNandwani/python/blob/master/numPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** Numpy stands for "Numerical Python".

It is a python extension module and not a programming language.

It provides fast and efficient operations on arrays of homogeneous data. **

**N-dimensional Array (ndarray Object)**

ndarray is multi-dimensional container which can contain only homogenous items.Shape of such array is defined by "shape" attribute.The datatype of the items inside an nd array is stored in an object known as 'dtype'.




In [3]:
import numpy as np

x= np.array([[1,2],[3,4]])
x.shape
print('x:\n', x)

x:
 [[1 2]
 [3 4]]


In [4]:
print('x:shape\n',x.shape)

x:shape
 (2, 2)


In [5]:
# total number of elements of the array is returned by the size
x.size

4

In [6]:
# number of axis (dimensions) of the array 
# ndim~number of dimensions
print('x:\n', x.ndim)

x:
 2


In [7]:
# datatype of homogenous array
print('x:\n',x.dtype)

x:
 int64


In [12]:
# exercise

#  8 (=64/8)

array=np.arange(64)
array.size

64

**Making a ndarray object**

np.empty  -creates unintialized numpy array of given shape and size


In [18]:
arr=np.empty(shape=[2,2],dtype=int)

print('arr:\n',arr)

arr:
 [[       47633888               0]
 [139676554301392               0]]


**np.zeros**

creates numpy aarray of given size and given type initialized with errors


In [19]:
np.zeros(shape=[2,3],dtype="float",order='c')

array([[0., 0., 0.],
       [0., 0., 0.]])

**np.ones**

In [20]:
np.ones(shape=[3,3],dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

**np.arange**

In [21]:
# np.arange(start,stop,step,dtype)
np.arange(start=100,stop=1000,step=200,dtype=int)

array([100, 300, 500, 700, 900])

**np.linespace**

it return evenly spaced numbers over a specified interval


In [25]:
print(np.linspace(start=2,stop=10,endpoint=True,retstep=2))

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]), 0.16326530612244897)


In [28]:
np.array([np.empty(shape=[1,3]),np.zeros(shape=[1,3]),np.ones(shape=[1,3])],dtype=int)

array([[[10,  0,  1]],

       [[ 0,  0,  0]],

       [[ 1,  1,  1]]])

**Array Element Accessing**

In [0]:
x=np.arange(50,100)

In [32]:
x[4]

54

In [37]:
# using slice object, x[start,stop,step]
print('X[5:35:11]\n',x[2:33:1])

X[5:35:11]
 [52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82]


In [39]:
# using tuple of splice object

print('x\n:',x[40:])

x
: [90 91 92 93 94 95 96 97 98 99]


In [48]:
task=np.arange(90,100,1)

print(task[[3,7,8]])
print(task[[-3,-7,-8]])

[93 97 98]
[97 93 92]
